### ISSUE TITLE
Facebook not show tags!

### ISSUE THREAD

**Issue by leomask101193** [ktquez/vue-head#34]

**Comment by bigbadwoolfe** [comment]
That's because Facebook will not read dynamic tags. They don't process JS at all. So if you want to get your OG tags to work, they have to be generated on the server. Setting them on the front end will work if you inspect the markup, but will not make any difference to Facebook. Facebook, unfortunately, only looks at the initial response.

**Comment by unusec** [comment]
@leomask101193  You can try to use netlify for hosting they have prerendering along with other cool stuff

**Comment by AndrewFedor** [comment]
Check out this package, it's a Webpack plugin that allows you to pre-render the component.

https://github.com/chrisvfritz/prerender-spa-plugin

I just had the same problem and was able to fix it with this. Cheers.
